
services:
  # Maven container to run tests
  tests:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: maven-tests
    working_dir: /app
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    command: >
      sh -c "mvn clean test && find target/allure-results -type f -name '*.json' -exec curl -X POST -F 'files[]=@{}' http://allure:5050/allure-docker-service/send-results \\;"

  # Allure backend service
  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-service
    ports:
      - "5050:5050" # API
    volumes:
      - allure-results:/app/allure-results
      - allure-reports:/app/allure-reports

  # Allure UI
  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure-ui
    ports:
      - "5252:5252" # UI
    environment:
      - ALLURE_DOCKER_PUBLIC_API_URL=http://localhost:5050
    depends_on:
      - allure

volumes:
  maven-repo:
  allure-results:
  allure-reports:
